//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Iteration
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Iteration()
    {
        this.Story_Iteration = new HashSet<Story_Iteration>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Story_Iteration> Story_Iteration { get; set; }
}

public partial class Member
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Member()
    {
        this.Member_Task = new HashSet<Member_Task>();
        this.Project_Member_Role = new HashSet<Project_Member_Role>();
        this.Work_flow = new HashSet<Work_flow>();
        this.Tasks = new HashSet<Task>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string E_mail { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Member_Task> Member_Task { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project_Member_Role> Project_Member_Role { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Work_flow> Work_flow { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Task> Tasks { get; set; }
}

public partial class Member_Task
{
    public int TaskID { get; set; }
    public int MemberID { get; set; }

    public virtual Member Member { get; set; }
}

public partial class Project
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Project()
    {
        this.Project_Member_Role = new HashSet<Project_Member_Role>();
        this.Stories = new HashSet<Story>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public string Description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project_Member_Role> Project_Member_Role { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Story> Stories { get; set; }
}

public partial class Project_Member_Role
{
    public int ProjectID { get; set; }
    public int RoleID { get; set; }
    public int MemberID { get; set; }

    public virtual Member Member { get; set; }
    public virtual Project Project { get; set; }
    public virtual Role Role { get; set; }
}

public partial class Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {
        this.Project_Member_Role = new HashSet<Project_Member_Role>();
    }

    public int ID { get; set; }
    public string Authority { get; set; }
    public string Description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project_Member_Role> Project_Member_Role { get; set; }
}

public partial class Story
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Story()
    {
        this.Story_Iteration = new HashSet<Story_Iteration>();
        this.Story1 = new HashSet<Story>();
        this.Tasks = new HashSet<Task>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public double Points { get; set; }
    public string Description { get; set; }
    public int ProjectID { get; set; }
    public Nullable<int> MainStory { get; set; }
    public string Status { get; set; }
    public int EstimatedHours { get; set; }

    public virtual Project Project { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Story_Iteration> Story_Iteration { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Story> Story1 { get; set; }
    public virtual Story Story2 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Task> Tasks { get; set; }
}

public partial class Story_Iteration
{
    public int StoryID { get; set; }
    public int IterationID { get; set; }
    public int SpentTime { get; set; }
    public string Status { get; set; }

    public virtual Iteration Iteration { get; set; }
    public virtual Story Story { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Task
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Task()
    {
        this.Work_flow = new HashSet<Work_flow>();
        this.Members = new HashSet<Member>();
    }

    public int ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int Estimated_Hours { get; set; }
    public string Status { get; set; }
    public int StoryID { get; set; }

    public virtual Story Story { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Work_flow> Work_flow { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Member> Members { get; set; }
}

public partial class Work_flow
{
    public int ID { get; set; }
    public System.DateTime Date { get; set; }
    public int SpentTime { get; set; }
    public int TaskID { get; set; }
    public int MemberID { get; set; }

    public virtual Member Member { get; set; }
    public virtual Task Task { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}

public partial class TaskData_Result
{
    public int ID { get; set; }
    public string Task_Name { get; set; }
    public string Description { get; set; }
    public int Estimated_Hours { get; set; }
    public string Status { get; set; }
}
